# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# compile C with /usr/bin/cc
C_FLAGS =  -fopenmp -fPIC -I/net/cremi/hanaba/M1/S2/pmc/project/pmcproject/trunk/fichiers/libsotl/include -I/net/cremi/hanaba/M1/S2/pmc/project/pmcproject/trunk/fichiers/libsotl    -std=c99 -g -O3 -Wno-deprecated -Wall -Wextra -Wno-unused-function

C_DEFINES = -DHAVE_LIBGL -DHAVE_OMP -DOCL_INCLUDE=\"/net/cremi/hanaba/M1/S2/pmc/project/pmcproject/trunk/fichiers/libsotl/include\" -DPROGRAM_NAME=\"/net/cremi/hanaba/M1/S2/pmc/project/pmcproject/trunk/fichiers/libsotl/kernel/physics.cl\" -DSHADERS_FILES_DIR=\"/net/cremi/hanaba/M1/S2/pmc/project/pmcproject/trunk/fichiers/libsotl/src\" -DUSE_DOUBLE=0 -Dsotl_EXPORTS

